name: Lighthouse Check
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@1.0
        with:
          theme_root: ./dist
          store: ${{ secrets.SHOP_STORE }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          product_handle: ${{ secrets.SHOP_PRODUCT_HANDLE }}
          collection_handle: ${{ secrets.SHOP_COLLECTION_HANDLE }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          lhci_min_score_performance: 0.6
          lhci_min_score_accessibility: 0.9

