name: Validate Pull Requests

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: ['staging']
    types: ['opened', 'edited', 'reopened', 'synchronize']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-and-build:
    name: Install and Compile Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: yarn install and build
        run: |
          yarn install
          yarn build
      - name: Archive compiled artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distribution_folder
          path: dist

  shopify_theme_check:
    name: Theme Check
    runs-on: ubuntu-latest
    needs: install-and-build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: 'distribution_folder'
          path: ./dist
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: Display structure of downloaded files
        run: ls -R
        
      - uses: actions/checkout@v2
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: './dist'
          token: ${{ github.token }}
          base: main
